name: RSpec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - rails-version: 7.1.0
          - rails-version: 7.2.0
          - rails-version: 8.0.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - run: bundle install
      env:
        RAILS_VERSION: ${{ matrix.rails-version }}
    - run: bundle exec rspec spec
      env:
        RAILS_VERSION: ${{ matrix.rails-version }}
